<a href="https://colab.research.google.com/github/pdh21/OCF_PVmapper/blob/main/Example_DeepNet.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

![](https://avatars.githubusercontent.com/u/48357542?s=200&v=4)

## PV mapping Example:
[Peter Hurley](http://pdh21.github.io/) 

In this notebook, we will give a simple example of training a deep net to detect solar panels from remote sensing data. 

As with most neural net projects, we need to:
1. Define training data: input tensors and target tensors.
2. Define a network of layers (or model ) that maps inputs to targets.
3. Configure the learning process by choosing a loss function, an optimizer
some metrics to monitor.
4. Iterate on training data by calling the fit() method of your model.

In [2]:
from google.colab import drive

drive.mount('/content/gdrive/MyDrive/PVmapping/')

Mounted at /content/gdrive


In [21]:
pip install tensorflow-io

     |████████████████████████████████| 25.3MB 1.5MB/s 


In [22]:
import os, sys, math
import numpy as np
from matplotlib import pyplot as plt
import tensorflow as tf
import tensorflow_io as tfio
print("Tensorflow version " + tf.__version__)

Tensorflow version 2.4.1


In [12]:
filenames_dataset = tf.data.Dataset.list_files('./*/*.tif')

In [24]:
def decode_tif_and_label(filename):
  bits = tf.io.read_file(filename)
  image = tfio.experimental.image.decode_tiff(bits)
  tmp=filename.split(['/_'])
  if filename.contains('binary'):
    label=
  label=[tmp[0],]
  return image

In [26]:
image_dataset = filenames_dataset.map(decode_tif)

In [29]:
for i in image_dataset:
  print(i)

Streaming output truncated to the last 5000 lines.
tf.Tensor(
[[[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 ...

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]], shape=(81, 81, 4), dtype=uint8)
tf.Tensor(
[[[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0

KeyboardInterrupt: ignored